server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: DEBUG                            # Hibernate SQL 로깅 레벨
    org.hibernate.type.descriptor.sql.BasicTypeDescriptor: TRACE  # Hibernate의 SQL 타입 디스크립터 로깅 레벨
    org.springframework.security: TRACE

spring:
  application:
    name: MSAfreeboard
  # spring 관련 설정이 이곳에 들어갑니다.
  
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/db?serverTimezone=Asia/Seoul
    username: root
    password: 1234

  jpa:
    hibernate:
#      ddl-auto: create
      ddl-auto: none
    properties:
      hibernate.format_sql: true
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true

  servlet:           # Multipart 파일 업로드 설정
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB  # 요청 최대 크기
      file-size-threshold: 0  # 파일 크기 임계값
      enabled: true

  jwt:
    secret: mySuperSecretKey  # JWT 비밀 키 설정